package br.com.conding.tv.resources

object GenericsStrings {
    const val PROJECT_NAME = "Spring Sale"
    const val CREATE_ONE_ACCOUNT = "Criar uma conta"
    const val EMAIL = "Email"
    const val PASSWORD = "Senha"
    const val OR = "ou"
    const val ENTER_YOUR_ACCOUNT = "Acessar minha conta"
    const val FORGOT_PASS = "Esqueceu sua senha?"
    const val NOT_BLANK_OR_EMPTY = "Preencha todos os campos!"
    const val VERSION = "Versão:"
    const val YOUR_ACTION = "Você deseja?"
    const val EMPTY_TEXT = ""
    const val WARNING = "Atenção!"
    const val CHANGE_TO_OTHER_ACCOUNT = "Trocar de conta"
    const val EXIT = "Sair do Programa"
    const val CATEGORIES = "Categorias"
    const val PRODUCTS = "Produtos"
    const val SETTINGS = "Configurações"
    const val ID = "Código"
    const val CATEGORY_NAME = "Nome da categoria"
    const val NEW_NAME_CATEGORY = "Novo nome da categoria"
    const val SAVE_CATEGORY = "Salvar categoria"
    const val EDIT_CATEGORY = "Editar categoria"
    const val DELETE_CATEGORY = "Apagar categoria"
    const val ADD_CATEGORIES = "Adicionar categorias"
    const val NO_CATEGORIES_SELECTED = "Nenhuma categoria selecionada"
    const val CANCEL = "Cancelar"
    const val CONFIRM = "Confirmar"
    const val SEARCH = "Pesquisar"
    const val SIZE_LIST = "Tamanho da lista"
    const val LOADING = "Carregando…"
    const val HOME = "Home"
    const val ALERT = "Alerta!"
    const val ACTUAL_NAME = "Nome atual"
    const val NAME = "Nome"
    const val NUMBER = "Número"
    const val ADJUSTMENTS = "Ajustes"
}
